In [2]:
#1-way --> General way

row = int(input())
col = int(input())

print("Enter elements in row-wise")

#input matrix
mat = []
for i in range(row):
    a = []
    for j in range(col):
        a.append(int(input()))
    mat.append(a)
    
# printing matrix
for i in range(row):
    for j in range(col):
        print(mat[i][j],end=' ')
    print()

3
3
Enter elements in row-wise
1
2
3
4
5
6
7
8
9
1 2 3 
4 5 6 
7 8 9 


In [8]:
# 2-way using numpy moudule

import numpy as np

row = int(input())
col = int(input())

a = list(map(int,input().split(' ')))
mat = np.array(a).reshape(row,col)
print(mat)

3
3
1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
# 3-way --> using oneliner

r = int(input())
c = int(input())
mat = [[int(input()) for x in range (r)] for y in range(c)]
print(mat[0])
print(mat[1])
print(mat[2])

3
3
2
3
4
5
6
7
8
9
1
[2, 3, 4]
[5, 6, 7]
[8, 9, 1]
